# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-25 20:59
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='\u63a5\u6536\u7528\u6237')),
                ('message', models.CharField(max_length=500, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6d88\u606f',
                'verbose_name_plural': '\u7528\u6237\u6d88\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', DjangoUeditor.models.UEditorField(verbose_name='\u63d0\u95ee\u5185\u5bb9')),
                ('answer', DjangoUeditor.models.UEditorField(verbose_name='\u8001\u5e08\u56de\u7b54')),
                ('question_status', models.IntegerField(choices=[(1, '\u5df2\u56de\u7b54'), (0, '\u672a\u56de\u7b54')], default=0, verbose_name='\u662f\u5426\u5df2\u7ecf\u56de\u7b54')),
                ('user_question_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u63d0\u95ee\u65f6\u95f4')),
                ('teacher_answer_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u56de\u7b54\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u63d0\u95ee\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u95ee\u9898\u56de\u7b54',
                'verbose_name_plural': '\u7528\u6237\u95ee\u9898\u56de\u7b54',
            },
        ),
    ]
